### PR TITLE
Remove Python 2 support

### PR DESCRIPTION
**Pull request by ejeschke**
- next release of ginga will be python 3 only.  Makes sense to remove
  support for Python 2 in qplan as well

### CODE REVIEW

**Comment by ejeschke** [comment]
@rdk1024, can you check the changes in `filetypes` are ok?

**Comment by ejeschke** [comment]
@rdk1024, looks like `qcheck.cgi` needs to be converted to python 3.

**Comment by ejeschke** [comment]
Rebased.

**Comment by rdk1024** [comment]
Confirmed that "Python 3 only" changes are ok in filetypes.py. Also, updated qcheck.cgi and promsdb.py to run in Python 3.

**Comment by ejeschke** [comment]
@rdk1024, I rebased against all the recent changes.  Can you check that all of your stuff is working as advertised?  I think we can think about a merge soon.

**Comment by rdk1024** [comment]
qcheck.cgi and related scripts are ok on the python3-only branch.

**Comment by ejeschke** [comment]
Rebased.

**Pull request merged**
